/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel.management;

/**
 *
 * @author Christian Devera
 */
import java.util.*;
import javax.swing.*;
import java.awt.*;

import javax.swing.ImageIcon;
import javax.swing.Timer;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import java.awt.Font;
import java.awt.Color;
import java.util.Locale;
import java.util.ResourceBundle;
public class ForgotPassword extends javax.swing.JFrame {
     int mouseX; 
      int mouseY;
      private LinkedList<userAccount> accounts;
        private ResourceBundle bundle;
        private LanguageManager lang;
        private ImageIcon enIcon;
      private ImageIcon jpIcon;
      private ImageIcon phIcon;
    public ForgotPassword(LinkedList<userAccount> accounts, String languageCode) {
        this.accounts = accounts;
        initComponents();
         Locale currentLocale = Locale.ENGLISH;  // or Locale.JAPAN, new Locale("tl", "PH"), etc.
    bundle = ResourceBundle.getBundle("hotel.management.Messages", currentLocale);
        
        
         jLabel15.setVisible(false);
         jPanel5.setVisible(false);
        setupCustomUI();
        
 enIcon = new ImageIcon(getClass().getResource("/resource/icons/english.png"));
  jpIcon = new ImageIcon(getClass().getResource("/resource/icons/japanese.png"));
   phIcon = new ImageIcon(getClass().getResource("/resource/icons/filipino.png"));
      lang = new LanguageManager();
lang.setLanguage(languageCode);
applyLanguage();
       
    }
private void applyLanguage() {
    
    jLabelTitle.setText(lang.get("forgot.title"));
    jLabelUsername.setText(lang.get("forgot.username"));
    jLabelEmail.setText(lang.get("forgot.email"));
    jLabelNewPassword.setText(lang.get("forgot.newpassword"));
    jLabelConfirmPassword.setText(lang.get("forgot.confirmpassword"));
    jButtonUpdate.setText(lang.get("forgot.update"));
    jLabelWelcome.setText(lang.get("forgot.welcome"));
    jLabelHeader.setText(lang.get("forgot.header"));
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel(){
            @Override
            public void paintComponent(Graphics g){
                Graphics2D g2 = (Graphics2D)g;
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(new Color(111, 80, 45));
                g2.fillRoundRect(0,0,getWidth(),getHeight(),40,40);
            }

        }
        ;
        dropdownLabel = new javax.swing.JLabel();
        dropdownPanel = new hotel.management.dropdownPanel();
        labelEnglish = new javax.swing.JLabel();
        labelFilipino = new javax.swing.JLabel();
        labelJapanese = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButtonUpdate = new javax.swing.JButton();
        jLabelUsername = new javax.swing.JLabel();
        jLabelNewPassword = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabelWelcome = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabelEmail = new javax.swing.JLabel();
        jLabelConfirmPassword = new javax.swing.JLabel();
        jPasswordField3 = new javax.swing.JPasswordField();
        jTextField3 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabelHeader = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        btnMinimize1 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        btnExit1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("login");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 239, 200));
        jPanel2.setLayout(null);

        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel3MouseReleased(evt);
            }
        });

        dropdownLabel.setBackground(new java.awt.Color(255, 255, 255));
        dropdownLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        dropdownLabel.setForeground(new java.awt.Color(255, 255, 255));
        dropdownLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/english.png"))); // NOI18N
        dropdownLabel.setText("English");
        dropdownLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dropdownLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dropdownLabelMouseEntered(evt);
            }
        });
        jPanel3.add(dropdownLabel);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(420, 10, 120, 40);

        labelEnglish.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        labelEnglish.setForeground(new java.awt.Color(255, 255, 255));
        labelEnglish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/english.png"))); // NOI18N
        labelEnglish.setText("English");
        labelEnglish.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelEnglish.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelEnglishMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelEnglishMouseEntered(evt);
            }
        });

        labelFilipino.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        labelFilipino.setForeground(new java.awt.Color(255, 255, 255));
        labelFilipino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/filipino.png"))); // NOI18N
        labelFilipino.setText("Filipino");
        labelFilipino.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelFilipino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelFilipinoMouseClicked(evt);
            }
        });

        labelJapanese.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        labelJapanese.setForeground(new java.awt.Color(255, 255, 255));
        labelJapanese.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/japanese.png"))); // NOI18N
        labelJapanese.setText("Japanese");
        labelJapanese.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelJapanese.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelJapaneseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout dropdownPanelLayout = new javax.swing.GroupLayout(dropdownPanel);
        dropdownPanel.setLayout(dropdownPanelLayout);
        dropdownPanelLayout.setHorizontalGroup(
            dropdownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dropdownPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dropdownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dropdownPanelLayout.createSequentialGroup()
                        .addGroup(dropdownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelEnglish)
                            .addComponent(labelFilipino))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(labelJapanese, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        dropdownPanelLayout.setVerticalGroup(
            dropdownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dropdownPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelEnglish)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelFilipino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelJapanese)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(dropdownPanel);
        dropdownPanel.setBounds(420, 60, 120, 110);
        dropdownPanel.setVisible(false);

        jPanel4.setBackground(new java.awt.Color(252, 244, 222));
        jPanel4.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(221, 190, 153), 2, true), javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15)));
        jPanel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel4MouseDragged(evt);
            }
        });
        jPanel4.setLayout(null);

        jLabelTitle.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(111, 78, 55));
        jLabelTitle.setText("FORGOT PASSWORD");
        jPanel4.add(jLabelTitle);
        jLabelTitle.setBounds(70, 0, 240, 48);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/management/loading gif effect.gif"))); // NOI18N
        jPanel4.add(jLabel15);
        jLabel15.setBounds(190, 250, 70, 90);

        jButtonUpdate.setBackground(new java.awt.Color(255, 202, 40));
        jButtonUpdate.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButtonUpdate.setForeground(new java.awt.Color(111, 80, 45));
        jButtonUpdate.setText("UPDATE");
        jButtonUpdate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(185, 152, 123), 1, true));
        jButtonUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonUpdateMouseClicked(evt);
            }
        });
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonUpdate);
        jButtonUpdate.setBounds(40, 300, 263, 40);

        jLabelUsername.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabelUsername.setForeground(new java.awt.Color(111, 78, 55));
        jLabelUsername.setText("Username:");
        jPanel4.add(jLabelUsername);
        jLabelUsername.setBounds(50, 100, 75, 30);

        jLabelNewPassword.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabelNewPassword.setForeground(new java.awt.Color(111, 78, 55));
        jLabelNewPassword.setText("New Password:");
        jPanel4.add(jLabelNewPassword);
        jLabelNewPassword.setBounds(30, 200, 110, 30);

        jPanel5.setBackground(new java.awt.Color(255, 230, 230));
        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel5.setLayout(null);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/management/red warning sign.png"))); // NOI18N
        jPanel5.add(jLabel20);
        jLabel20.setBounds(0, -10, 60, 50);

        jLabel21.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 51, 51));
        jLabel21.setText("\"Incorrect username or password. Try again.\"");
        jPanel5.add(jLabel21);
        jLabel21.setBounds(20, 0, 261, 30);

        jPanel4.add(jPanel5);
        jPanel5.setBounds(10, 60, 310, 30);

        jLabelWelcome.setBackground(new java.awt.Color(111, 80, 55));
        jLabelWelcome.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabelWelcome.setForeground(new java.awt.Color(80, 50, 30));
        jLabelWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWelcome.setText("Welcome, enjoy a warm and comforting time");
        jPanel4.add(jLabelWelcome);
        jLabelWelcome.setBounds(10, 40, 300, 30);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/management/JAVABEE(40X40).png"))); // NOI18N
        jPanel4.add(jLabel23);
        jLabel23.setBounds(10, 0, 80, 50);

        jPasswordField2.setBackground(new java.awt.Color(255, 250, 240));
        jPasswordField2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jPasswordField2.setForeground(new java.awt.Color(111, 80, 45));
        jPasswordField2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(221, 190, 153), 1, true));
        jPanel4.add(jPasswordField2);
        jPasswordField2.setBounds(150, 200, 150, 31);

        jLabelEmail.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabelEmail.setForeground(new java.awt.Color(111, 80, 45));
        jLabelEmail.setText("Email:");
        jPanel4.add(jLabelEmail);
        jLabelEmail.setBounds(80, 150, 50, 30);

        jLabelConfirmPassword.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabelConfirmPassword.setForeground(new java.awt.Color(111, 80, 45));
        jLabelConfirmPassword.setText("Confirm Password:");
        jPanel4.add(jLabelConfirmPassword);
        jLabelConfirmPassword.setBounds(10, 250, 140, 30);

        jPasswordField3.setBackground(new java.awt.Color(255, 250, 240));
        jPasswordField3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jPasswordField3.setForeground(new java.awt.Color(111, 80, 45));
        jPasswordField3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(221, 190, 153), 1, true));
        jPasswordField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField3ActionPerformed(evt);
            }
        });
        jPanel4.add(jPasswordField3);
        jPasswordField3.setBounds(150, 250, 150, 31);

        jTextField3.setBackground(new java.awt.Color(255, 250, 240));
        jTextField3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(60, 42, 33));
        jTextField3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(221, 190, 153), 1, true));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField3);
        jTextField3.setBounds(150, 100, 150, 31);

        jTextField2.setBackground(new java.awt.Color(255, 250, 240));
        jTextField2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(60, 42, 33));
        jTextField2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(221, 190, 153), 1, true));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField2);
        jTextField2.setBounds(150, 150, 150, 31);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(130, 120, 330, 360);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 550, 560));

        jPanel6.setBackground(new java.awt.Color(255, 255, 220));
        jPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(80, 50, 30)));
        jPanel6.setLayout(null);

        jLabelHeader.setBackground(new java.awt.Color(111, 80, 55));
        jLabelHeader.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelHeader.setForeground(new java.awt.Color(80, 50, 30));
        jLabelHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHeader.setText("“Brewed with love, served with comfort.”  ");
        jPanel6.add(jLabelHeader);
        jLabelHeader.setBounds(340, 0, 490, 40);

        jLabel24.setBackground(new java.awt.Color(111, 80, 55));
        jLabel24.setFont(new java.awt.Font("Algerian", 1, 26)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(80, 50, 30));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("JAVABEE EXPRESS");
        jPanel6.add(jLabel24);
        jLabel24.setBounds(20, -20, 300, 90);

        btnMinimize1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMinimize1.setForeground(new java.awt.Color(111, 78, 60));
        btnMinimize1.setText("—");
        btnMinimize1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        btnMinimize1.setBorderPainted(false);
        btnMinimize1.setContentAreaFilled(false);
        btnMinimize1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimize1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimize1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinimize1MouseExited(evt);
            }
        });
        btnMinimize1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimize1ActionPerformed(evt);
            }
        });
        jPanel6.add(btnMinimize1);
        btnMinimize1.setBounds(980, 0, 40, 40);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/management/coffee icons.png"))); // NOI18N
        jPanel6.add(jLabel25);
        jLabel25.setBounds(10, 0, 40, 40);

        btnExit1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnExit1.setForeground(new java.awt.Color(111, 78, 60));
        btnExit1.setText("X");
        btnExit1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        btnExit1.setBorderPainted(false);
        btnExit1.setFocusPainted(false);
        btnExit1.setContentAreaFilled(false);
        btnExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExit1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExit1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExit1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnExit1MousePressed(evt);
            }
        });
        btnExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExit1ActionPerformed(evt);
            }
        });
        jPanel6.add(btnExit1);
        btnExit1.setBounds(1020, 0, 40, 40);

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/management/javabeee.jpg"))); // NOI18N
        jLabel1.setText(" ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 510, 550));

        jLabel2.setBackground(new java.awt.Color(228, 227, 233));
        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("We are close. Come back at 9:00 A.M.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 430, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/management/javabeenight.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 510, 590));

        setSize(new java.awt.Dimension(1061, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButtonUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUpdateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUpdateMouseClicked

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
 jLabel15.setVisible(true);    // Show loading animation
    jButtonUpdate.setEnabled(false);   // Prevent multiple clicks

    SwingWorker<Void, Void> worker = new SwingWorker<>() {
        String result = null;

        @Override
        protected Void doInBackground() throws Exception {
            // Simulate delay
            Thread.sleep(2000);

            // Get inputs
            String username = jTextField3.getText().trim();
            String email = jTextField2.getText().trim();
            String newPassword = new String(jPasswordField2.getPassword());
            String confirmPassword = new String(jPasswordField3.getPassword());

           
            result = userAccount.resetPassword(username, email, newPassword, confirmPassword, accounts);
            return null;
        }

        @Override
        protected void done() {
            jLabel15.setVisible(false); 
            jButtonUpdate.setEnabled(true); 
          
            if (result == null) {
                JOptionPane.showMessageDialog(null, bundle.getString("forgot.success.password_updated"));
                new Login(accounts).setVisible(true);
                dispose(); // Close current window
            } else {
                 jLabel21.setText(LanguageManager.get(result));
                jPanel5.setVisible(true); // Show error panel
            }
        }
    };

    worker.execute();
      
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jPanel4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseDragged

    }//GEN-LAST:event_jPanel4MouseDragged

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void btnMinimize1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimize1MouseClicked
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinimize1MouseClicked

    private void btnMinimize1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimize1MouseEntered
        btnMinimize1.setOpaque(true);
        btnMinimize1.setBackground(Color.lightGray); // or new Color(255, 102, 102)
        btnMinimize1.setContentAreaFilled(true);
    }//GEN-LAST:event_btnMinimize1MouseEntered

    private void btnMinimize1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimize1MouseExited
        btnMinimize1.setOpaque(false);
        btnMinimize1.setContentAreaFilled(false);
    }//GEN-LAST:event_btnMinimize1MouseExited

    private void btnMinimize1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimize1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMinimize1ActionPerformed

    private void btnExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExit1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnExit1MouseClicked

    private void btnExit1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExit1MouseEntered
        btnExit1.setOpaque(true);
        btnExit1.setBackground(Color.RED); // hover = red
    }//GEN-LAST:event_btnExit1MouseEntered

    private void btnExit1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExit1MouseExited
        btnExit1.setOpaque(false);
        btnExit1.setBackground(null); // back to no background
    }//GEN-LAST:event_btnExit1MouseExited

    private void btnExit1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExit1MousePressed
        btnExit1.setOpaque(true);
        btnExit1.setBackground(Color.RED); // keep red when pressed
    }//GEN-LAST:event_btnExit1MousePressed

    private void btnExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExit1ActionPerformed

    private void dropdownLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dropdownLabelMouseClicked

    }//GEN-LAST:event_dropdownLabelMouseClicked

    private void dropdownLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dropdownLabelMouseEntered
        dropdownPanel.setVisible(true);
    }//GEN-LAST:event_dropdownLabelMouseEntered

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered

    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseReleased

    }//GEN-LAST:event_jPanel3MouseReleased

    private void labelEnglishMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEnglishMouseClicked
        dropdownLabel.setText("English");
        dropdownLabel.setIcon(enIcon);
        dropdownPanel.setVisible(false);
        lang.setLanguage("en");
        applyLanguage();
    }//GEN-LAST:event_labelEnglishMouseClicked

    private void labelEnglishMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEnglishMouseEntered

    }//GEN-LAST:event_labelEnglishMouseEntered

    private void labelFilipinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelFilipinoMouseClicked
        dropdownLabel.setText("Filipino");
        dropdownLabel.setIcon(phIcon);
        dropdownPanel.setVisible(false);
        lang.setLanguage("tl");
        applyLanguage();
    }//GEN-LAST:event_labelFilipinoMouseClicked

    private void labelJapaneseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelJapaneseMouseClicked
        dropdownLabel.setText("Japanese");
        dropdownLabel.setIcon(jpIcon);
        dropdownPanel.setVisible(false);
        lang.setLanguage("ja");
        applyLanguage();
    }//GEN-LAST:event_labelJapaneseMouseClicked
private void setupCustomUI() {
    setIconImage(new ImageIcon(getClass().getResource("iconn.png")).getImage());
    

    btnMinimize1.setOpaque(false);
    btnMinimize1.setContentAreaFilled(false);
    btnMinimize1.setBorderPainted(false);
    btnMinimize1.setFocusable(false);

 
   
    jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mousePressed(java.awt.event.MouseEvent evt) {
            mouseX = evt.getX();
            mouseY = evt.getY();
        }   
    });

    jPanel6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
        public void mouseDragged(java.awt.event.MouseEvent evt) {
            int x = evt.getXOnScreen();
            int y = evt.getYOnScreen();
            setLocation(x - mouseX, y - mouseY);
        }
    });
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        LinkedList<userAccount> accounts = new LinkedList<>();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit1;
    private javax.swing.JButton btnMinimize1;
    private javax.swing.JLabel dropdownLabel;
    private hotel.management.dropdownPanel dropdownPanel;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelConfirmPassword;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelHeader;
    private javax.swing.JLabel jLabelNewPassword;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JLabel jLabelWelcome;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel labelEnglish;
    private javax.swing.JLabel labelFilipino;
    private javax.swing.JLabel labelJapanese;
    // End of variables declaration//GEN-END:variables
}
