/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel.management;

/**
 *
 * @author Christian Devera
 */
import java.util.*;
import javax.swing.*;

import javax.swing.ImageIcon;
import javax.swing.Timer;
import java.awt.*;
import javax.swing.plaf.basic.BasicComboBoxUI;

public class HomeePage extends javax.swing.JFrame {

    /**
     * Creates new form HomeePage
     */
    private  LinkedList<userAccount> accounts;
private  userAccount currentUser;
 private ImageIcon enIcon;
      private ImageIcon jpIcon;
      private ImageIcon phIcon;
      private LanguageManager lang;
      int mouseX;
      int mouseY;
 
    public HomeePage(LinkedList<userAccount> accounts, userAccount currentUser, String languageCode) {
        initComponents();
            jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {
     "Profile", "Sign out"
}));
        
         
        setupCustomUI();
        
        
        enIcon = new ImageIcon(getClass().getResource("/resource/icons/english.png"));
  jpIcon = new ImageIcon(getClass().getResource("/resource/icons/japanese.png"));
   phIcon = new ImageIcon(getClass().getResource("/resource/icons/filipino.png"));
  this.accounts = accounts;
this.currentUser = currentUser;
lang = new LanguageManager();
lang.setLanguage(languageCode);
applyLanguage();
    
        jButtonOrder.setFocusPainted(false);
jButtonOrder.setBorder(BorderFactory.createEmptyBorder(10, 20, 10, 20));
jButtonOrder.setBackground(new Color(111, 80, 45));
jButtonOrder.setForeground(Color.WHITE);
jButtonOrder.setFont(new Font("SansSerif", Font.BOLD, 18));

jButtonOrder.addMouseListener(new java.awt.event.MouseAdapter() {
    public void mousePressed(java.awt.event.MouseEvent evt) {
        jButtonOrder.setBackground(new Color(254, 201, 13)); // press color
    }
    public void mouseReleased(java.awt.event.MouseEvent evt) {
        jButtonOrder.setBackground(new Color(111, 80, 45)); // default color
    }
});

ImageIcon profileIcon = new ImageIcon(getClass().getResource("/hotel/management/user.png"));

jComboBox2.setRenderer(new DefaultListCellRenderer() {
    @Override
    public Component getListCellRendererComponent(JList<?> list, Object value, int index,
                                                  boolean isSelected, boolean cellHasFocus) {
        JLabel label = (JLabel) super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);

        // When index is -1, it's the *collapsed (default) view*
        if (index == -1) {
            label.setIcon(profileIcon);
            label.setText(""); // hide text
        } else {
            label.setIcon(null);
            label.setText(value.toString());
        }
        return label;
    }
});

jComboBox2.setUI(new BasicComboBoxUI() {
    @Override
    protected JButton createArrowButton() {
        return new JButton() {
            @Override
            public int getWidth() {
                return 0; // Hide arrow button
            }
        };
    }
});
    }
    
    

    private void applyLanguage() {
    jLabelHeader.setText(LanguageManager.get("homepage.header"));
    jLabelGreetings1.setText(LanguageManager.get("homepage.greeting1"));
    jLabelGreetings2.setText(LanguageManager.get("homepage.greetings2"));
    jLabelGreetings3.setText(LanguageManager.get("homepage.greetings3"));
    jButtonOrder.setText(LanguageManager.get("homepage.order"));
    jLabelHello.setText(LanguageManager.get("homepage.hello") + currentUser.getUsername());
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabelHeader = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        btnMinimize1 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        btnExit1 = new javax.swing.JButton();
        jLabelHello = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelGreetings1 = new javax.swing.JLabel();
        jLabelGreetings2 = new javax.swing.JLabel();
        jLabelGreetings3 = new javax.swing.JLabel();
        jButtonOrder = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel(){
            @Override
            public void paintComponent(Graphics g){
                Graphics2D g2 = (Graphics2D)g;
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(new Color(111, 80, 45));
                g2.fillRoundRect(0,0,getWidth(),getHeight(),40,40);
            }

        }
        ;
        dropdownLabel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel(){
            @Override
            public void paintComponent(Graphics g){
                Graphics2D g2 = (Graphics2D)g;
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(new Color(111, 80, 45));
                g2.fillRoundRect(0,0,getWidth(),getHeight(),40,40);
            }

        }
        ;
        dropdownLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel(){
            @Override
            public void paintComponent(Graphics g){
                Graphics2D g2 = (Graphics2D)g;
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(new Color(111, 80, 45));
                g2.fillRoundRect(0,0,getWidth(),getHeight(),40,40);
            }

        }
        ;
        dropdownLabel3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel(){
            @Override
            public void paintComponent(Graphics g){
                Graphics2D g2 = (Graphics2D)g;
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(new Color(111, 80, 45));
                g2.fillRoundRect(0,0,getWidth(),getHeight(),40,40);
            }

        }
        ;
        dropdownLabel4 = new javax.swing.JLabel();
        dropdownPanel1 = new hotel.management.dropdownPanel();
        labelEnglish1 = new javax.swing.JLabel();
        labelFilipino1 = new javax.swing.JLabel();
        labelJapanese1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 220));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(80, 50, 30)));
        jPanel5.setLayout(null);

        jLabelHeader.setBackground(new java.awt.Color(111, 80, 55));
        jLabelHeader.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelHeader.setForeground(new java.awt.Color(80, 50, 30));
        jLabelHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHeader.setText("“Brewed with love, served with comfort.”  ");
        jPanel5.add(jLabelHeader);
        jLabelHeader.setBounds(310, 0, 510, 40);

        jLabel21.setBackground(new java.awt.Color(111, 80, 55));
        jLabel21.setFont(new java.awt.Font("Algerian", 1, 26)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(80, 50, 30));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("JAVABEE EXPRESS");
        jPanel5.add(jLabel21);
        jLabel21.setBounds(20, -20, 300, 90);

        btnMinimize1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMinimize1.setForeground(new java.awt.Color(111, 78, 60));
        btnMinimize1.setText("—");
        btnMinimize1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        btnMinimize1.setBorderPainted(false);
        btnMinimize1.setFocusPainted(false);
        btnMinimize1.setContentAreaFilled(false);
        btnMinimize1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimize1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimize1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinimize1MouseExited(evt);
            }
        });
        btnMinimize1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimize1ActionPerformed(evt);
            }
        });
        jPanel5.add(btnMinimize1);
        btnMinimize1.setBounds(1220, 0, 40, 40);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/management/coffee icons.png"))); // NOI18N
        jPanel5.add(jLabel22);
        jLabel22.setBounds(10, 0, 40, 40);

        btnExit1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnExit1.setForeground(new java.awt.Color(111, 78, 60));
        btnExit1.setText("X");
        btnExit1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        btnExit1.setBorderPainted(false);
        btnExit1.setFocusPainted(false);
        btnExit1.setContentAreaFilled(false);
        btnExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExit1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExit1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExit1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnExit1MousePressed(evt);
            }
        });
        btnExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExit1ActionPerformed(evt);
            }
        });
        jPanel5.add(btnExit1);
        btnExit1.setBounds(1260, 0, 40, 40);

        jLabelHello.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelHello.setText("Hello");
        jPanel5.add(jLabelHello);
        jLabelHello.setBounds(860, 10, 180, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Profile", "Sign out", " " }));
        jComboBox2.setOpaque(false);
        jComboBox2.setBorder(null);
        jComboBox2.setFocusable(false);
        jComboBox2.setBackground(new Color(0,0,0,0)); // transparent
        jComboBox2.setPreferredSize(new Dimension(26, 26)); // Adjust as needed
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel5.add(jComboBox2);
        jComboBox2.setBounds(1020, 10, 80, 30);

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 40));

        jPanel2.setPreferredSize(new java.awt.Dimension(1250, 650));
        jPanel2.setLayout(null);

        jPanel1.setBackground(new Color(255, 255, 255, 100));
        jPanel1.setOpaque(true);

        jLabelGreetings1.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        jLabelGreetings1.setForeground(new java.awt.Color(111, 80, 45));
        jLabelGreetings1.setText("JAVA");

        jLabelGreetings2.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        jLabelGreetings2.setForeground(new java.awt.Color(111, 80, 45));
        jLabelGreetings2.setText("GOOD");

        jLabelGreetings3.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        jLabelGreetings3.setForeground(new java.awt.Color(111, 80, 45));
        jLabelGreetings3.setText("DAY!");

        jButtonOrder.setBackground(new java.awt.Color(111, 80, 45));
        jButtonOrder.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButtonOrder.setForeground(new java.awt.Color(255, 255, 255));
        jButtonOrder.setText("ORDER NOW");
        jButtonOrder.setBorder(javax.swing.BorderFactory.createEmptyBorder(19, 20, 10, 20));
        jButtonOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(561, 561, 561)
                        .addComponent(jLabelGreetings1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(553, 553, 553)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelGreetings2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButtonOrder)
                                .addComponent(jLabelGreetings3)))))
                .addContainerGap(591, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelGreetings1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelGreetings2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelGreetings3)
                .addGap(18, 18, 18)
                .addComponent(jButtonOrder)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1);
        jPanel1.setBounds(0, 170, 1290, 290);

        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel4MouseReleased(evt);
            }
        });

        dropdownLabel.setBackground(new java.awt.Color(255, 255, 255));
        dropdownLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        dropdownLabel.setForeground(new java.awt.Color(255, 255, 255));
        dropdownLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/english.png"))); // NOI18N
        dropdownLabel.setText("English");
        dropdownLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dropdownLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dropdownLabelMouseEntered(evt);
            }
        });
        jPanel4.add(dropdownLabel);

        jPanel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel6MouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel6MouseReleased(evt);
            }
        });

        dropdownLabel2.setBackground(new java.awt.Color(255, 255, 255));
        dropdownLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        dropdownLabel2.setForeground(new java.awt.Color(255, 255, 255));
        dropdownLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/english.png"))); // NOI18N
        dropdownLabel2.setText("English");
        dropdownLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dropdownLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dropdownLabel2MouseEntered(evt);
            }
        });
        jPanel6.add(dropdownLabel2);

        jPanel4.add(jPanel6);

        jPanel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel7MouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel7MouseReleased(evt);
            }
        });

        dropdownLabel3.setBackground(new java.awt.Color(255, 255, 255));
        dropdownLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        dropdownLabel3.setForeground(new java.awt.Color(255, 255, 255));
        dropdownLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/english.png"))); // NOI18N
        dropdownLabel3.setText("English");
        dropdownLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dropdownLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dropdownLabel3MouseEntered(evt);
            }
        });
        jPanel7.add(dropdownLabel3);

        jPanel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel8MouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel8MouseReleased(evt);
            }
        });

        dropdownLabel4.setBackground(new java.awt.Color(255, 255, 255));
        dropdownLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        dropdownLabel4.setForeground(new java.awt.Color(255, 255, 255));
        dropdownLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/english.png"))); // NOI18N
        dropdownLabel4.setText("English");
        dropdownLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dropdownLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dropdownLabel4MouseEntered(evt);
            }
        });
        jPanel8.add(dropdownLabel4);

        jPanel7.add(jPanel8);

        jPanel4.add(jPanel7);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(1170, 10, 120, 40);

        labelEnglish1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        labelEnglish1.setForeground(new java.awt.Color(255, 255, 255));
        labelEnglish1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/english.png"))); // NOI18N
        labelEnglish1.setText("English");
        labelEnglish1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelEnglish1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelEnglish1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelEnglish1MouseEntered(evt);
            }
        });

        labelFilipino1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        labelFilipino1.setForeground(new java.awt.Color(255, 255, 255));
        labelFilipino1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/filipino.png"))); // NOI18N
        labelFilipino1.setText("Filipino");
        labelFilipino1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelFilipino1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelFilipino1MouseClicked(evt);
            }
        });

        labelJapanese1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        labelJapanese1.setForeground(new java.awt.Color(255, 255, 255));
        labelJapanese1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/japanese.png"))); // NOI18N
        labelJapanese1.setText("Japanese");
        labelJapanese1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelJapanese1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelJapanese1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout dropdownPanel1Layout = new javax.swing.GroupLayout(dropdownPanel1);
        dropdownPanel1.setLayout(dropdownPanel1Layout);
        dropdownPanel1Layout.setHorizontalGroup(
            dropdownPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dropdownPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dropdownPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dropdownPanel1Layout.createSequentialGroup()
                        .addGroup(dropdownPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelEnglish1)
                            .addComponent(labelFilipino1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(labelJapanese1, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                .addContainerGap())
        );
        dropdownPanel1Layout.setVerticalGroup(
            dropdownPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dropdownPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelEnglish1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelFilipino1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelJapanese1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(dropdownPanel1);
        dropdownPanel1.setBounds(1170, 60, 120, 110);
        dropdownPanel1.setVisible(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/ulit3.gif"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 10, 1300, 640);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 36, 1300, 660));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinimize1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimize1MouseClicked
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinimize1MouseClicked

    private void btnMinimize1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimize1MouseEntered
        btnMinimize1.setOpaque(true);
        btnMinimize1.setBackground(Color.lightGray); // or new Color(255, 102, 102)
        btnMinimize1.setContentAreaFilled(true);
    }//GEN-LAST:event_btnMinimize1MouseEntered

    private void btnMinimize1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimize1MouseExited
        btnMinimize1.setOpaque(false);
        btnMinimize1.setContentAreaFilled(false);
    }//GEN-LAST:event_btnMinimize1MouseExited

    private void btnMinimize1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimize1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMinimize1ActionPerformed

    private void btnExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExit1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnExit1MouseClicked

    private void btnExit1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExit1MouseEntered
        btnExit1.setOpaque(true);
        btnExit1.setBackground(Color.RED); // hover = red
    }//GEN-LAST:event_btnExit1MouseEntered

    private void btnExit1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExit1MouseExited
        btnExit1.setOpaque(false);
        btnExit1.setBackground(null); // back to no background
    }//GEN-LAST:event_btnExit1MouseExited

    private void btnExit1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExit1MousePressed
        btnExit1.setOpaque(true);
        btnExit1.setBackground(Color.RED); // keep red when pressed
    }//GEN-LAST:event_btnExit1MousePressed

    private void btnExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExit1ActionPerformed

    private void jButtonOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrderActionPerformed
        Dashboard dash = new Dashboard(accounts, currentUser);
    dash.setVisible(true);
    dispose();
    }//GEN-LAST:event_jButtonOrderActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
           int selectedIndex = jComboBox2.getSelectedIndex();

    if (selectedIndex == 0) {
        JOptionPane.showMessageDialog(null, "Opening profile...");
    } else if (selectedIndex == 1) {
        int confirm = JOptionPane.showConfirmDialog(null, "Do you want to sign out?");
        if (confirm == JOptionPane.YES_OPTION) {
            Login login = new Login(accounts);
            login.setVisible(true);
            this.dispose();
        }
    }

    // Reset to "Profile" after action
    jComboBox2.setSelectedIndex(-1);
    
    }//GEN-LAST:event_jComboBox2ActionPerformed

           
    private void labelEnglish1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEnglish1MouseClicked
        dropdownLabel.setText("English");
        dropdownLabel.setIcon(enIcon);
        dropdownPanel1.setVisible(false);
        lang.setLanguage("en");
        applyLanguage();
    }//GEN-LAST:event_labelEnglish1MouseClicked

    private void labelEnglish1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEnglish1MouseEntered

    }//GEN-LAST:event_labelEnglish1MouseEntered

    private void labelFilipino1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelFilipino1MouseClicked
        dropdownLabel.setText("Filipino");
        dropdownLabel.setIcon(phIcon);
        dropdownPanel1.setVisible(false);
        lang.setLanguage("tl");
        applyLanguage();
    }//GEN-LAST:event_labelFilipino1MouseClicked

    private void labelJapanese1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelJapanese1MouseClicked
        dropdownLabel.setText("Japanese");
        dropdownLabel.setIcon(jpIcon);
        dropdownPanel1.setVisible(false);
        lang.setLanguage("ja");
        applyLanguage();
    }//GEN-LAST:event_labelJapanese1MouseClicked

    private void dropdownLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dropdownLabelMouseClicked

    }//GEN-LAST:event_dropdownLabelMouseClicked

    private void dropdownLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dropdownLabelMouseEntered
        dropdownPanel1.setVisible(true);
    }//GEN-LAST:event_dropdownLabelMouseEntered

    private void dropdownLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dropdownLabel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dropdownLabel2MouseClicked

    private void dropdownLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dropdownLabel2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_dropdownLabel2MouseEntered

    private void jPanel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MouseEntered

    private void jPanel6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MouseReleased

    private void dropdownLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dropdownLabel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dropdownLabel3MouseClicked

    private void dropdownLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dropdownLabel3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_dropdownLabel3MouseEntered

    private void dropdownLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dropdownLabel4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dropdownLabel4MouseClicked

    private void dropdownLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dropdownLabel4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_dropdownLabel4MouseEntered

    private void jPanel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel8MouseEntered

    private void jPanel8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel8MouseReleased

    private void jPanel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel7MouseEntered

    private void jPanel7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel7MouseReleased

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered

    }//GEN-LAST:event_jPanel4MouseEntered

    private void jPanel4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseReleased

    }//GEN-LAST:event_jPanel4MouseReleased

    private void setupCustomUI() {
    setIconImage(new ImageIcon(getClass().getResource("iconn.png")).getImage());
   
    btnMinimize1.setOpaque(false);
    btnMinimize1.setContentAreaFilled(false);
    btnMinimize1.setBorderPainted(false);
    btnMinimize1.setFocusable(false);

 
    
    jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mousePressed(java.awt.event.MouseEvent evt) {
            mouseX = evt.getX();
            mouseY = evt.getY();
        }
    });

    jPanel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
        public void mouseDragged(java.awt.event.MouseEvent evt) {
            int x = evt.getXOnScreen();
            int y = evt.getYOnScreen();
            setLocation(x - mouseX, y - mouseY);
        }
    });
}
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit1;
    private javax.swing.JButton btnMinimize1;
    private javax.swing.JLabel dropdownLabel;
    private javax.swing.JLabel dropdownLabel2;
    private javax.swing.JLabel dropdownLabel3;
    private javax.swing.JLabel dropdownLabel4;
    private hotel.management.dropdownPanel dropdownPanel1;
    private javax.swing.JButton jButtonOrder;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabelGreetings1;
    private javax.swing.JLabel jLabelGreetings2;
    private javax.swing.JLabel jLabelGreetings3;
    private javax.swing.JLabel jLabelHeader;
    private javax.swing.JLabel jLabelHello;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel labelEnglish1;
    private javax.swing.JLabel labelFilipino1;
    private javax.swing.JLabel labelJapanese1;
    // End of variables declaration//GEN-END:variables
}
