/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel.management;

import java.util.*;
import javax.swing.*;

import javax.swing.ImageIcon;
import javax.swing.Timer;
import java.awt.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.border.*;
import java.awt.Color;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

 class Login extends javax.swing.JFrame {
     private LanguageManager lang;
      int mouseX; 
      int mouseY;
      private boolean isNight = false;  
      private ImageIcon enIcon;
      private ImageIcon jpIcon;
      private ImageIcon phIcon;

     private LinkedList<userAccount> accounts;

    public Login(LinkedList<userAccount> accounts) {
        initComponents();
        
      
      
    
   




 
 enIcon = new ImageIcon(getClass().getResource("/resource/icons/english.png"));
  jpIcon = new ImageIcon(getClass().getResource("/resource/icons/japanese.png"));
   phIcon = new ImageIcon(getClass().getResource("/resource/icons/filipino.png"));
        lang = new LanguageManager();
        lang.setLanguage("en"); 
          
        applyLanguage();
   


        ImageIcon icon = new ImageIcon(getClass().getResource("/hotel/management/javabeee_1.jpg"));
Image image = icon.getImage().getScaledInstance(520, 570, Image.SCALE_SMOOTH);
jLabel1.setIcon(new ImageIcon(image));
  ImageIcon icons = new ImageIcon(getClass().getResource("/hotel/management/javabeenight.jpg"));
Image images = icons.getImage().getScaledInstance(520, 570, Image.SCALE_SMOOTH);
jLabel3.setIcon(new ImageIcon(images));
      
        this.accounts = accounts;
        
         jLabel10.setVisible(false);
         jPanel4.setVisible(false);
         jLabel3.setVisible(false);

        setupCustomUI();
        
        
    }
    
    

        

       public void setLoginPanelEnabled(boolean enabled) {
    jPanel1.setEnabled(enabled);
    for (Component component : jPanel1.getComponents()) {
        component.setEnabled(enabled);
    }
}
       
       
     
    
    private void applyLanguage() {
        jLabelTitle.setText(lang.get("login.title"));
        jLabelUsername.setText(lang.get("login.username"));
        jLabelPassword.setText(lang.get("login.password"));
        jButtonLogin.setText(lang.get("login.button"));
        jCheckBoxRemember.setText(lang.get("login.remember"));
        jLabelForgot.setText(lang.get("login.forgot"));
        jLabelRegister.setText(lang.get("login.register"));
        jLabelNoAccount.setText(lang.get("login.noaccount"));
        jLabelWelcome.setText(lang.get("login.welcome"));
        jLabelHeader.setText(lang.get("login.header"));
        jLabelClose.setText(lang.get("login.close"));
    }
    

    /**x`
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jLabel1 = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel(){
            @Override
            public void paintComponent(Graphics g){
                Graphics2D g2 = (Graphics2D)g;
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(new Color(111, 80, 45));
                g2.fillRoundRect(0,0,getWidth(),getHeight(),40,40);
            }

        }
        ;
        dropdownLabel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel(){
            @Override
            public void paintComponent(Graphics g){
                Graphics2D g2 = (Graphics2D)g;
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(new Color(111, 80, 45));
                g2.fillRoundRect(0,0,getWidth(),getHeight(),40,40);
            }

        }
        ;
        dropdownLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel(){
            @Override
            public void paintComponent(Graphics g){
                Graphics2D g2 = (Graphics2D)g;
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(new Color(111, 80, 45));
                g2.fillRoundRect(0,0,getWidth(),getHeight(),40,40);
            }

        }
        ;
        dropdownLabel2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel(){
            @Override
            public void paintComponent(Graphics g){
                Graphics2D g2 = (Graphics2D)g;
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(new Color(111, 80, 45));
                g2.fillRoundRect(0,0,getWidth(),getHeight(),40,40);
            }

        }
        ;
        dropdownLabel3 = new javax.swing.JLabel();
        dropdownPanel = new hotel.management.dropdownPanel();
        labelEnglish = new javax.swing.JLabel();
        labelFilipino = new javax.swing.JLabel();
        labelJapanese = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jLabelForgot = new javax.swing.JLabel();
        jButtonLogin = new javax.swing.JButton();
        jLabelNoAccount = new javax.swing.JLabel();
        jLabelRegister = new javax.swing.JLabel();
        jLabelUsername = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jCheckBoxRemember =  new JCheckBox("Remember me") {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);

                if (isSelected()) {
                    // Draw custom check box background
                    g.setColor(new Color(255, 202, 40)); // yellow fill
                    g.fillRect(1, 1, 16, 16); // Checkbox square

                    // Draw check mark manually
                    g.setColor(new Color(111, 80, 45)); // brown check
                    g.drawLine(4, 9, 7, 12);
                    g.drawLine(7, 12, 12, 5);
                } else {
                    // draw unselected square
                    g.setColor(Color.LIGHT_GRAY);
                    g.drawRect(1, 1, 16, 16);
                }
            }
        };
        jCheckBoxRemember.setOpaque(false); // To avoid default background
        jCheckBoxRemember.setFocusPainted(false);
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabelWelcome = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabelHeader = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        btnMinimize1 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        btnExit1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("login");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/management/javabeee.jpg"))); // NOI18N
        jLabel1.setText(" ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 510, 550));
        jLabel1.getAccessibleContext().setAccessibleName("jLabel1");

        jLabelClose.setBackground(new java.awt.Color(228, 227, 233));
        jLabelClose.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setText("Were Closed. Please come back at 9:00 A.M.");
        jLabelClose.setRequestFocusEnabled(false);
        getContentPane().add(jLabelClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 490, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/management/javabeenight.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 510, 590));

        jPanel2.setBackground(new java.awt.Color(255, 239, 200));
        jPanel2.setLayout(null);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/management/day and nigth.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 10, 40, 40);

        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel3MouseReleased(evt);
            }
        });

        dropdownLabel.setBackground(new java.awt.Color(255, 255, 255));
        dropdownLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        dropdownLabel.setForeground(new java.awt.Color(255, 255, 255));
        dropdownLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/english.png"))); // NOI18N
        dropdownLabel.setText("English");
        dropdownLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dropdownLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dropdownLabelMouseEntered(evt);
            }
        });
        jPanel3.add(dropdownLabel);

        jPanel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel6MouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel6MouseReleased(evt);
            }
        });

        dropdownLabel1.setBackground(new java.awt.Color(255, 255, 255));
        dropdownLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        dropdownLabel1.setForeground(new java.awt.Color(255, 255, 255));
        dropdownLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/english.png"))); // NOI18N
        dropdownLabel1.setText("English");
        dropdownLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dropdownLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dropdownLabel1MouseEntered(evt);
            }
        });
        jPanel6.add(dropdownLabel1);

        jPanel3.add(jPanel6);

        jPanel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel7MouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel7MouseReleased(evt);
            }
        });

        dropdownLabel2.setBackground(new java.awt.Color(255, 255, 255));
        dropdownLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        dropdownLabel2.setForeground(new java.awt.Color(255, 255, 255));
        dropdownLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/english.png"))); // NOI18N
        dropdownLabel2.setText("English");
        dropdownLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dropdownLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dropdownLabel2MouseEntered(evt);
            }
        });
        jPanel7.add(dropdownLabel2);

        jPanel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel8MouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel8MouseReleased(evt);
            }
        });

        dropdownLabel3.setBackground(new java.awt.Color(255, 255, 255));
        dropdownLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        dropdownLabel3.setForeground(new java.awt.Color(255, 255, 255));
        dropdownLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/english.png"))); // NOI18N
        dropdownLabel3.setText("English");
        dropdownLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dropdownLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dropdownLabel3MouseEntered(evt);
            }
        });
        jPanel8.add(dropdownLabel3);

        jPanel7.add(jPanel8);

        jPanel3.add(jPanel7);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(420, 10, 120, 40);

        labelEnglish.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        labelEnglish.setForeground(new java.awt.Color(255, 255, 255));
        labelEnglish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/english.png"))); // NOI18N
        labelEnglish.setText("English");
        labelEnglish.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelEnglish.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelEnglishMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelEnglishMouseEntered(evt);
            }
        });

        labelFilipino.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        labelFilipino.setForeground(new java.awt.Color(255, 255, 255));
        labelFilipino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/filipino.png"))); // NOI18N
        labelFilipino.setText("Filipino");
        labelFilipino.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelFilipino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelFilipinoMouseClicked(evt);
            }
        });

        labelJapanese.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        labelJapanese.setForeground(new java.awt.Color(255, 255, 255));
        labelJapanese.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/japanese.png"))); // NOI18N
        labelJapanese.setText("Japanese");
        labelJapanese.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelJapanese.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelJapaneseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout dropdownPanelLayout = new javax.swing.GroupLayout(dropdownPanel);
        dropdownPanel.setLayout(dropdownPanelLayout);
        dropdownPanelLayout.setHorizontalGroup(
            dropdownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dropdownPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dropdownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dropdownPanelLayout.createSequentialGroup()
                        .addGroup(dropdownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelEnglish)
                            .addComponent(labelFilipino))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(labelJapanese, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        dropdownPanelLayout.setVerticalGroup(
            dropdownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dropdownPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelEnglish)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelFilipino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelJapanese)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(dropdownPanel);
        dropdownPanel.setBounds(420, 60, 120, 110);
        dropdownPanel.setVisible(false);

        jPanel1.setBackground(new java.awt.Color(252, 244, 222));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(221, 190, 153), 2, true), javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15)));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.setLayout(null);

        jLabelTitle.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(111, 78, 55));
        jLabelTitle.setText("LOGIN");
        jPanel1.add(jLabelTitle);
        jLabelTitle.setBounds(130, 0, 93, 48);

        jTextField1.setBackground(new java.awt.Color(255, 250, 240));
        jTextField1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(60, 42, 33));
        jTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(221, 190, 153), 1, true));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(130, 100, 173, 31);

        jPasswordField1.setBackground(new java.awt.Color(255, 250, 240));
        jPasswordField1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(60, 42, 33));
        jPasswordField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(221, 190, 153), 1, true));
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(130, 150, 173, 34);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/management/loading gif effect.gif"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(160, 200, 70, 70);
        jLabel10.getAccessibleContext().setAccessibleName("LoadingSpinner");
        jLabel10.getAccessibleContext().setAccessibleDescription("");

        jLabelForgot.setBackground(new java.awt.Color(254, 201, 13));
        jLabelForgot.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabelForgot.setForeground(new java.awt.Color(111, 78, 55));
        jLabelForgot.setText("<html><u>Forgot Password?</u></html>");
        jLabelForgot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelForgot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelForgotMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelForgotMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelForgotMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelForgotMousePressed(evt);
            }
        });
        jPanel1.add(jLabelForgot);
        jLabelForgot.setBounds(200, 200, 101, 16);

        jButtonLogin.setBackground(new java.awt.Color(255, 202, 40));
        jButtonLogin.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButtonLogin.setForeground(new java.awt.Color(51, 51, 51));
        jButtonLogin.setText("Log In");
        jButtonLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(185, 152, 123), 1, true));
        jButtonLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLoginMouseClicked(evt);
            }
        });
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLogin);
        jButtonLogin.setBounds(50, 250, 263, 40);

        jLabelNoAccount.setBackground(new java.awt.Color(254, 201, 13));
        jLabelNoAccount.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabelNoAccount.setForeground(new java.awt.Color(111, 78, 55));
        jLabelNoAccount.setText("Don't have an account?");
        jPanel1.add(jLabelNoAccount);
        jLabelNoAccount.setBounds(50, 310, 127, 16);

        jLabelRegister.setBackground(new java.awt.Color(254, 201, 13));
        jLabelRegister.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabelRegister.setForeground(new java.awt.Color(111, 78, 55));
        jLabelRegister.setText("<html><u>Register</u></html>");
        jLabelRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRegisterMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelRegister);
        jLabelRegister.setBounds(180, 310, 70, 16);

        jLabelUsername.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabelUsername.setForeground(new java.awt.Color(111, 78, 55));
        jLabelUsername.setText("Username:");
        jPanel1.add(jLabelUsername);
        jLabelUsername.setBounds(40, 100, 75, 26);

        jLabelPassword.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabelPassword.setForeground(new java.awt.Color(111, 78, 55));
        jLabelPassword.setText("Password:");
        jPanel1.add(jLabelPassword);
        jLabelPassword.setBounds(40, 160, 72, 19);

        jCheckBoxRemember.setBackground(new java.awt.Color(252, 244, 222));
        jCheckBoxRemember.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jCheckBoxRemember.setForeground(new java.awt.Color(111, 80, 40));
        jCheckBoxRemember.setText("Remember me");
        jCheckBoxRemember.setContentAreaFilled(false);
        jCheckBoxRemember.setFocusPainted(false);
        jCheckBoxRemember.setBorderPainted(false);
        jPanel1.add(jCheckBoxRemember);
        jCheckBoxRemember.setBounds(40, 200, 110, 20);

        jPanel4.setBackground(new java.awt.Color(255, 230, 230));
        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel4.setLayout(null);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/management/red warning sign.png"))); // NOI18N
        jPanel4.add(jLabel14);
        jLabel14.setBounds(0, -10, 60, 50);

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 51, 51));
        jLabel13.setText("\"Incorrect username or password. Try again.\"");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(20, 0, 290, 30);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(10, 60, 310, 30);

        jLabelWelcome.setBackground(new java.awt.Color(111, 80, 55));
        jLabelWelcome.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelWelcome.setForeground(new java.awt.Color(111, 80, 45));
        jLabelWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWelcome.setText("Welcome, enjoy a warm and comforting time");
        jPanel1.add(jLabelWelcome);
        jLabelWelcome.setBounds(30, 40, 280, 20);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/management/JAVABEE(40X40).png"))); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(10, 0, 80, 50);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(130, 140, 330, 360);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 550, 560));

        jPanel5.setBackground(new java.awt.Color(255, 255, 220));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(80, 50, 30)));
        jPanel5.setLayout(null);

        jLabelHeader.setBackground(new java.awt.Color(111, 80, 55));
        jLabelHeader.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelHeader.setForeground(new java.awt.Color(80, 50, 30));
        jLabelHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHeader.setText("“Brewed with love, served with comfort.”  ");
        jPanel5.add(jLabelHeader);
        jLabelHeader.setBounds(340, 0, 490, 40);

        jLabel21.setBackground(new java.awt.Color(111, 80, 55));
        jLabel21.setFont(new java.awt.Font("Algerian", 1, 26)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(80, 50, 30));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("JAVABEE EXPRESS");
        jPanel5.add(jLabel21);
        jLabel21.setBounds(20, -20, 300, 90);

        btnMinimize1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMinimize1.setForeground(new java.awt.Color(111, 78, 60));
        btnMinimize1.setText("—");
        btnMinimize1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        btnMinimize1.setFocusPainted(false);
        btnMinimize1.setBorderPainted(false);
        btnMinimize1.setContentAreaFilled(false);
        btnMinimize1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimize1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimize1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinimize1MouseExited(evt);
            }
        });
        btnMinimize1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimize1ActionPerformed(evt);
            }
        });
        jPanel5.add(btnMinimize1);
        btnMinimize1.setBounds(980, 0, 40, 40);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/management/coffee icons.png"))); // NOI18N
        jPanel5.add(jLabel22);
        jLabel22.setBounds(10, 0, 40, 40);

        btnExit1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnExit1.setForeground(new java.awt.Color(111, 78, 60));
        btnExit1.setText("X");
        btnExit1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        btnExit1.setFocusPainted(false);
        btnExit1.setBorderPainted(false);
        btnExit1.setContentAreaFilled(false);
        btnExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExit1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExit1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExit1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnExit1MousePressed(evt);
            }
        });
        btnExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExit1ActionPerformed(evt);
            }
        });
        jPanel5.add(btnExit1);
        btnExit1.setBounds(1020, 0, 40, 40);

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 40));

        setSize(new java.awt.Dimension(1059, 588));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
                                             
   jLabel10.setVisible(true);   // Always show loading animation first
    jPanel4.setVisible(false);   // Always hide error panel first
    jButtonLogin.setEnabled(false);  // Disable the login button
    
    SwingWorker<Void, Void> worker = new SwingWorker<>() {
        userAccount matchedUser = null;
        boolean missingFields = false;

        @Override
        protected Void doInBackground() throws Exception {
            Thread.sleep(1000);  // Simulate loading delay

            String username = jTextField1.getText().trim();
            String password = new String(jPasswordField1.getPassword()).trim();

            // Validate inputs
            if (username.isEmpty() || password.isEmpty()) {
                missingFields = true;
                return null;  // Stop here; don't check login
            }

            matchedUser = userAccount.login(username, password, accounts);
            return null;
        }

        @Override
        protected void done() {
            jLabel10.setVisible(false);   // Hide loading animation
            jButtonLogin.setEnabled(true);    // Re-enable login button

            if (missingFields) {
                jLabel13.setText(LanguageManager.get("login.error.empty"));

                jPanel4.setVisible(true);
            } else if (matchedUser != null) {
                String currentLangCode = lang.getCurrentLanguageCode(); // Add this me
                HomeePage home = new HomeePage(accounts, matchedUser, lang.getCurrentLanguageCode());
                home.setVisible(true);
                dispose();  // Close login window
            } else {
                jLabel13.setText(LanguageManager.get("login.error.invalid"));
                jPanel4.setVisible(true);
            }
        }
    };

    worker.execute();  // Start the background login chec
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jLabelForgotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelForgotMouseClicked
     String currentLangCode = lang.getCurrentLanguageCode(); // Add this me
        ForgotPassword forgot = new ForgotPassword(accounts, lang.getCurrentLanguageCode());
forgot.setVisible(true);

this.dispose();

    }//GEN-LAST:event_jLabelForgotMouseClicked

    private void jLabelForgotMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelForgotMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelForgotMousePressed

    private void jLabelForgotMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelForgotMouseEntered
        
    }//GEN-LAST:event_jLabelForgotMouseEntered

    private void jLabelForgotMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelForgotMouseExited
        // TODO add your handling code here:    
    }//GEN-LAST:event_jLabelForgotMouseExited

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
     
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jButtonLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoginMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLoginMouseClicked

    private void jLabelRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegisterMouseClicked
           String currentLangCode = lang.getCurrentLanguageCode(); // Add this me
        Register regForm = new Register(accounts, lang.getCurrentLanguageCode());
           regForm.setVisible(true);
           this.dispose();
    }//GEN-LAST:event_jLabelRegisterMouseClicked

    private void btnMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseClicked
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeMouseClicked

    private void btnMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseEntered
        btnMinimize1.setOpaque(true);
        btnMinimize1.setBackground(Color.RED);
        btnMinimize1.setContentAreaFilled(true);
    }//GEN-LAST:event_btnMinimizeMouseEntered

    private void btnMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseExited
        btnMinimize1.setOpaque(false);
        btnMinimize1.setContentAreaFilled(false);
    }//GEN-LAST:event_btnMinimizeMouseExited

    private void btnMinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMinimizeActionPerformed

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        btnExit1.setOpaque(true);
        btnExit1.setBackground(Color.RED); // or new Color(255, 102, 102)
        btnExit1.setContentAreaFilled(true);
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        btnExit1.setOpaque(false);
        btnExit1.setContentAreaFilled(false);
    }//GEN-LAST:event_btnExitMouseExited

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnMinimize1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimize1MouseClicked
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinimize1MouseClicked

    private void btnMinimize1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimize1MouseEntered
        btnMinimize1.setOpaque(true);
        btnMinimize1.setBackground(Color.lightGray); // or new Color(255, 102, 102)
        btnMinimize1.setContentAreaFilled(true);
    }//GEN-LAST:event_btnMinimize1MouseEntered

    private void btnMinimize1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimize1MouseExited
       btnMinimize1.setOpaque(false);
        btnMinimize1.setContentAreaFilled(false);
    }//GEN-LAST:event_btnMinimize1MouseExited

    private void btnMinimize1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimize1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMinimize1ActionPerformed

    private void btnExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExit1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnExit1MouseClicked

    private void btnExit1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExit1MouseEntered
      btnExit1.setOpaque(true);
    btnExit1.setBackground(Color.RED); // hover = red
    }//GEN-LAST:event_btnExit1MouseEntered

    private void btnExit1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExit1MouseExited
         btnExit1.setOpaque(false);
    btnExit1.setBackground(null); // back to no background
    }//GEN-LAST:event_btnExit1MouseExited

    private void btnExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExit1ActionPerformed

    private void btnExit1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExit1MousePressed
           btnExit1.setOpaque(true);
    btnExit1.setBackground(Color.RED); // keep red when pressed
    }//GEN-LAST:event_btnExit1MousePressed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        if (isNight) {
        jLabel1.setVisible(true);      // Show day
        jLabel3.setVisible(false);   // Hide night
        jLabel7.setText("Night");      // Change icon to moon
        setLoginPanelEnabled(true);
    } else {
       jLabel1.setVisible(false);     // Hide day
       jLabel3.setVisible(true);    // Show night
        jLabel7.setText("Day");      // Change icon to sun
       setLoginPanelEnabled(false);
    }
    isNight = !isNight;
    }//GEN-LAST:event_jLabel7MouseClicked

    private void dropdownLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dropdownLabelMouseClicked
      
        
       
    }//GEN-LAST:event_dropdownLabelMouseClicked

    private void labelEnglishMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEnglishMouseClicked
   dropdownLabel.setText("English");
        dropdownLabel.setIcon(enIcon);
        dropdownPanel.setVisible(false);
        lang.setLanguage("en");
        applyLanguage();
    }//GEN-LAST:event_labelEnglishMouseClicked

    private void labelFilipinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelFilipinoMouseClicked
         dropdownLabel.setText("Filipino");
        dropdownLabel.setIcon(phIcon);
        dropdownPanel.setVisible(false);
        lang.setLanguage("tl");
        applyLanguage();
    }//GEN-LAST:event_labelFilipinoMouseClicked

    private void labelJapaneseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelJapaneseMouseClicked
         dropdownLabel.setText("Japanese");
        dropdownLabel.setIcon(jpIcon);
        dropdownPanel.setVisible(false);
        lang.setLanguage("ja");
        applyLanguage();
    }//GEN-LAST:event_labelJapaneseMouseClicked

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
         
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseReleased
      
    }//GEN-LAST:event_jPanel3MouseReleased

    private void dropdownLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dropdownLabelMouseEntered
        dropdownPanel.setVisible(true); 
    }//GEN-LAST:event_dropdownLabelMouseEntered

    private void labelEnglishMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEnglishMouseEntered
         
    }//GEN-LAST:event_labelEnglishMouseEntered

    private void dropdownLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dropdownLabel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dropdownLabel1MouseClicked

    private void dropdownLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dropdownLabel1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_dropdownLabel1MouseEntered

    private void jPanel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MouseEntered

    private void jPanel6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MouseReleased

    private void dropdownLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dropdownLabel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dropdownLabel2MouseClicked

    private void dropdownLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dropdownLabel2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_dropdownLabel2MouseEntered

    private void dropdownLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dropdownLabel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dropdownLabel3MouseClicked

    private void dropdownLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dropdownLabel3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_dropdownLabel3MouseEntered

    private void jPanel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel8MouseEntered

    private void jPanel8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel8MouseReleased

    private void jPanel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel7MouseEntered

    private void jPanel7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel7MouseReleased
private void setupCustomUI() {
    setIconImage(new ImageIcon(getClass().getResource("iconn.png")).getImage());
   
    btnMinimize1.setOpaque(false);
    btnMinimize1.setContentAreaFilled(false);
    btnMinimize1.setBorderPainted(false);
    btnMinimize1.setFocusable(false);

 
    
    jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mousePressed(java.awt.event.MouseEvent evt) {
            mouseX = evt.getX();
            mouseY = evt.getY();
        }
    });

    jPanel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
        public void mouseDragged(java.awt.event.MouseEvent evt) {
            int x = evt.getXOnScreen();
            int y = evt.getYOnScreen();
            setLocation(x - mouseX, y - mouseY);
        }
    });
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit1;
    private javax.swing.JButton btnMinimize1;
    private javax.swing.JLabel dropdownLabel;
    private javax.swing.JLabel dropdownLabel1;
    private javax.swing.JLabel dropdownLabel2;
    private javax.swing.JLabel dropdownLabel3;
    private hotel.management.dropdownPanel dropdownPanel;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JCheckBox jCheckBoxRemember;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelForgot;
    private javax.swing.JLabel jLabelHeader;
    private javax.swing.JLabel jLabelNoAccount;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelRegister;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JLabel jLabelWelcome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelEnglish;
    private javax.swing.JLabel labelFilipino;
    private javax.swing.JLabel labelJapanese;
    // End of variables declaration//GEN-END:variables
}
