/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel.management;

import java.util.*;
import javax.swing.*;
import java.awt.*;
public class Register extends javax.swing.JFrame {
     int mouseX; 
      int mouseY;
     private LinkedList<userAccount> accounts;
    
    public Register(LinkedList<userAccount> accounts) {
         this.accounts = accounts;
        initComponents();
            jLabel16.setVisible(false);
        jPanel5.setVisible(false);

        setupCustomUI();
       
     
    }

    /**x`
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnMinimize = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        hide1 = new javax.swing.JLabel();
        show1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("login");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 220));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(80, 50, 30)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setBackground(new java.awt.Color(111, 80, 55));
        jLabel12.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(80, 50, 30));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("心温まるひとときを、どうぞお過ごしください心温まるひとときを、どうぞお過ごしください。");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 560, 50));

        jLabel13.setBackground(new java.awt.Color(111, 80, 55));
        jLabel13.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(80, 50, 30));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("JAVABEE EXPRESS");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -20, 390, 90));

        btnMinimize.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMinimize.setForeground(new java.awt.Color(111, 78, 60));
        btnMinimize.setText("—");
        btnMinimize.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        btnMinimize.setBorderPainted(false);
        btnMinimize.setContentAreaFilled(false);
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseExited(evt);
            }
        });
        btnMinimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizeActionPerformed(evt);
            }
        });
        jPanel3.add(btnMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, 40, 40));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/management/coffee png.png"))); // NOI18N
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, 40, 50));

        btnExit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(111, 78, 60));
        btnExit.setText("X");
        btnExit.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel3.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 0, 40, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/management/javabeee.jpg"))); // NOI18N
        jLabel3.setText(" ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 530, -1));

        jPanel2.setBackground(new java.awt.Color(255, 239, 200));
        jPanel2.setLayout(null);
        jPanel2.add(jTabbedPane1);
        jTabbedPane1.setBounds(260, 410, 0, 1);

        jPanel4.setBackground(new java.awt.Color(252, 244, 222));
        jPanel4.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(221, 190, 153), 2, true), javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15)));
        jPanel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel4MouseDragged(evt);
            }
        });
        jPanel4.setLayout(null);

        jLabel15.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(111, 78, 55));
        jLabel15.setText("SIGN UP");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(130, 0, 93, 48);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/management/loading gif effect.gif"))); // NOI18N
        jPanel4.add(jLabel16);
        jLabel16.setBounds(130, 120, 70, 90);

        jButton3.setBackground(new java.awt.Color(255, 202, 40));
        jButton3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(111, 80, 45));
        jButton3.setText("Register");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(185, 152, 123), 1, true));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3);
        jButton3.setBounds(40, 300, 263, 40);

        jLabel18.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(111, 78, 55));
        jLabel18.setText("Username:");
        jPanel4.add(jLabel18);
        jLabel18.setBounds(60, 100, 75, 30);

        jLabel19.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(111, 78, 55));
        jLabel19.setText("Contact Number:");
        jPanel4.add(jLabel19);
        jLabel19.setBounds(20, 200, 130, 30);

        hide1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/management/hide pass.png"))); // NOI18N
        hide1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hide1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                hide1MouseReleased(evt);
            }
        });
        jPanel4.add(hide1);
        hide1.setBounds(260, 260, 40, 20);

        show1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/management/show pass.png"))); // NOI18N
        show1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                show1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                show1MousePressed(evt);
            }
        });
        jPanel4.add(show1);
        show1.setBounds(260, 260, 40, 20);

        jPanel5.setBackground(new java.awt.Color(255, 230, 230));
        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel5.setLayout(null);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/management/red warning sign.png"))); // NOI18N
        jPanel5.add(jLabel20);
        jLabel20.setBounds(0, -10, 60, 50);

        jLabel21.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 51, 51));
        jLabel21.setText("\"Incorrect username or password. Try again.\"");
        jPanel5.add(jLabel21);
        jLabel21.setBounds(20, 0, 290, 30);

        jPanel4.add(jPanel5);
        jPanel5.setBounds(10, 60, 310, 30);

        jLabel22.setBackground(new java.awt.Color(111, 80, 55));
        jLabel22.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(80, 50, 30));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("ようこそ、心あたたまるひとときを。");
        jPanel4.add(jLabel22);
        jLabel22.setBounds(50, 40, 240, 30);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/management/JAVABEE(40X40).png"))); // NOI18N
        jPanel4.add(jLabel23);
        jLabel23.setBounds(20, 10, 80, 50);

        jLabel17.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(111, 80, 45));
        jLabel17.setText("Email:");
        jPanel4.add(jLabel17);
        jLabel17.setBounds(90, 140, 50, 50);

        jLabel24.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(111, 80, 45));
        jLabel24.setText(" Password:");
        jPanel4.add(jLabel24);
        jLabel24.setBounds(60, 250, 80, 30);

        jPasswordField1.setBackground(new java.awt.Color(255, 250, 240));
        jPasswordField1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(111, 80, 45));
        jPasswordField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(221, 190, 153), 1, true));
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel4.add(jPasswordField1);
        jPasswordField1.setBounds(150, 250, 150, 31);

        jTextField1.setBackground(new java.awt.Color(255, 250, 240));
        jTextField1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(60, 42, 33));
        jTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(221, 190, 153), 1, true));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField1);
        jTextField1.setBounds(150, 100, 150, 31);

        jTextField3.setBackground(new java.awt.Color(255, 250, 240));
        jTextField3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(60, 42, 33));
        jTextField3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(221, 190, 153), 1, true));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField3);
        jTextField3.setBounds(150, 200, 150, 31);

        jTextField2.setBackground(new java.awt.Color(255, 250, 240));
        jTextField2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(60, 42, 33));
        jTextField2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(221, 190, 153), 1, true));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField2);
        jTextField2.setBounds(150, 150, 150, 31);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(130, 120, 330, 360);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 540, 560));

        setSize(new java.awt.Dimension(1061, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseClicked
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeMouseClicked

    private void btnMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseEntered
        btnMinimize.setOpaque(true);
        btnMinimize.setBackground(Color.RED);
        btnMinimize.setContentAreaFilled(true);
    }//GEN-LAST:event_btnMinimizeMouseEntered

    private void btnMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseExited
        btnMinimize.setOpaque(false);
        btnMinimize.setContentAreaFilled(false);
    }//GEN-LAST:event_btnMinimizeMouseExited

    private void btnMinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMinimizeActionPerformed

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        btnExit.setOpaque(true);
        btnExit.setBackground(Color.RED); // or new Color(255, 102, 102)
        btnExit.setContentAreaFilled(true);
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        btnExit.setOpaque(false);
        btnExit.setContentAreaFilled(false);
    }//GEN-LAST:event_btnExitMouseExited

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            jLabel16.setVisible(true); 
    jButton3.setEnabled(false); 

    SwingWorker<Void, Void> worker = new SwingWorker<>() {
        String result = null;

        @Override
        protected Void doInBackground() throws Exception {
            Thread.sleep(2000); 

            String username = jTextField1.getText().trim();
            String password = new String(jPasswordField1.getPassword());
            String email = jTextField2.getText().trim();
            String contact = jTextField3.getText().trim();

            result = userAccount.register(username, password, email, contact, accounts);
            return null;
        }

        @Override
        protected void done() {
            jLabel16.setVisible(false); 
            jButton3.setEnabled(true);  

            if (result == null) {
                JOptionPane.showMessageDialog(null, "Registration successful!");
                new Login(accounts).setVisible(true);
                dispose();
            } else {
                jLabel21.setText(result); 
                jPanel5.setVisible(true); 
            }
        }
    };

    worker.execute();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jPanel4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseDragged

    }//GEN-LAST:event_jPanel4MouseDragged

    private void show1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_show1MousePressed

    private void show1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_show1MouseClicked

    private void hide1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hide1MouseReleased
        show1.setVisible(false);
        hide1.setVisible(true);
        jPasswordField1.setEchoChar('*');
    }//GEN-LAST:event_hide1MouseReleased

    private void hide1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hide1MousePressed
        show1.setVisible(true);
        hide1.setVisible(false);
        jPasswordField1.setEchoChar((char)0);
    }//GEN-LAST:event_hide1MousePressed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed
private void setupCustomUI() {
    setIconImage(new ImageIcon(getClass().getResource("iconn.png")).getImage());

    btnMinimize.setOpaque(false);
    btnMinimize.setContentAreaFilled(false);
    btnMinimize.setBorderPainted(false);
    btnMinimize.setFocusable(false);

 
   
    jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mousePressed(java.awt.event.MouseEvent evt) {
            mouseX = evt.getX();
            mouseY = evt.getY();
        }
    });

    jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
        public void mouseDragged(java.awt.event.MouseEvent evt) {
            int x = evt.getXOnScreen();
            int y = evt.getYOnScreen();
            setLocation(x - mouseX, y - mouseY);
        }
    });
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnMinimize;
    private javax.swing.JLabel hide1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel show1;
    // End of variables declaration//GEN-END:variables
}
